services:
  mysql:
    image: mysql:8.0
    container_name: closetBuddy-mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: closetBuddy
      MYSQL_DATABASE: closetBuddy
      MYSQL_USER: user
      MYSQL_PASSWORD: closetBuddy
      TZ: Asia/Seoul
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d