spring:
  application:
    name: closetBuddy
  security:
    user:
      name: user
      password: 1234

  datasource:
    url: jdbc:mysql://localhost:3306/closetBuddy_db?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: tuna372#5585

  jpa:
    hibernate:
      ddl-auto: create





jwt:
  secret:

springdoc:
  swagger-ui:
    path: /closetBuddy

server:
  port: 8084