spring:
  application:
    name: closetBuddy
  security:
    user:
      name:
      password:

  datasource:
    url:
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: create





jwt:
  secret:

springdoc:
  swagger-ui:
    path:

server:
  port: